### ISSUE TITLE
Investigate Python Stable ABI

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/rustworkx#891]
### What is the expected enhancement?

We should look into building rustworkx against the stable c abi instead of the version specific one that we use currently. I did this for qiskit in: https://github.com/Qiskit/qiskit-terra/pull/10120 and at least there it didn't look like there was any performance regression associated with the  change. Doing this will greatly reduce the number of binaries we'd have to publish at each release.

**Comment by IvanIsCoding** [comment]
Just a reminder to add `musllinux` images to the supported binaries. This was the `cibuildwheel` config that we used in 0.13.2 to launch it:
```
env:
          CIBW_BEFORE_ALL_LINUX: "apk add --no-cache curl gcc && curl https://sh.rustup.rs -sSf | sh -s -- -y && source $HOME/.cargo/env && rustup install stable && rustup default stable"
          CIBW_ENVIRONMENT_LINUX: 'PATH="$PATH:$HOME/.cargo/bin:$HOME/.cargo/env" CARGO_NET_GIT_FETCH_WITH_CLI="true"'
          CIBW_MUSLLINUX_X86_64_IMAGE: quay.io/pypa/musllinux_1_1_x86_64:latest
          CIBW_SKIP: cp36-* pp* *win32 *macosx* *manylinux* *686* *s390x* *aarch64*
          CIBW_BEFORE_BUILD: pip install -U setuptools-rust
          CIBW_TEST_REQUIRES: networkx testtools fixtures
          CIBW_BUILD_FRONTEND: "pip"
          CIBW_TEST_COMMAND: python -m unittest discover {project}/tests/rustworkx_tests
          CIBW_TEST_SKIP: cp312-* cp37-* cp38-*
```
